name = "Zen's Anti-Combat Logout"; // name
picture = ""; // picture in expanded description
logoSmall = ""; // icon next to mod name when description is not expanded
logo = ""; // logo below game menu
logoOver = ""; // on mouse hover over logo
tooltip = ""; // tool tip on mouse hover
overview = "Adds automated combat-logout detection and prevention functionality to server."; // overview
action = "https://zenarchist.io/"; // link
author = "Zenarchist"; // author
version = "1.0"; // version